project:
  type: website

website:
  title: "AAU Climate"
  navbar:
    background: "#276221"
    left:
      - text: "Home"
        file: index.qmd
      - text: "EMCC-X"
        file: emcc26.qmd
      - text: "Earth Day"
        menu:
          - sidebar:ed2025
          - sidebar:ed2024  
          - sidebar:ed2023
      - text: "Research Projects"
        file: climateeconometrics.qmd
        
  open-graph: true

  sidebar:
    - id: ed2023
      title: "2023"
      style: "docked"
      background: "light"
      contents:
        - text: "Earth Day 2023"
          file: previousevents/earthday2023.qmd
        - text: "Schedule"
          file: previousevents/earthday2023_schedule.qmd
        - text: "Hackathon"
          file: previousevents/earthday2023_hackathon.qmd
        - text: "Photo Gallery"
          file: previousevents/earthday2023_gallery.qmd

    - id: ed2024
      title: "2024"
      style: "docked"
      background: "light"
      contents:
        - text: "Earth Day 2024"
          file: earthday2024.qmd
        - text: "Schedule"
          file: earthday2024_schedule.qmd
        - text: "Research Presentations"
          file: earthday2024_researchpresentations.qmd
        - text: "Hackathon"
          file: earthday2024_hackathon.qmd
        - text: "Meme Competition"
          file: earthday2024_hackathon.qmd#meme-competition
        - text: "Photo Gallery"
          file: earthday2024_gallery.qmd
        - text: "Register"
          url: "https://forms.office.com/pages/responsepage.aspx?id=Sbrb9QbOb0msPgzxQ2HZNBkC2W4DGcxNs7tfQ8Mk3LJUMTNYWjNWWlgxTUlCVkNUWFNEMDRISkFVUC4u"
        - text: "Call for Speakers"
          file: earthday2024_callforspeakers.qmd

    - id: ed2025
      title: "2025"
      style: "docked"
      background: "light"
      contents:
        - text: "Earth Day 2025"
          file: earthday2025.qmd
        - text: "Schedule"
          file: earthday2025_schedule.qmd
        - text: "Hackathon"
          file: earthday2025_hackathon.qmd
        - text: "Photo Gallery"
          file: earthday2025_gallery.qmd
        - text: "Register"
          url: "https://forms.office.com/Pages/ResponsePage.aspx?id=Sbrb9QbOb0msPgzxQ2HZNBkC2W4DGcxNs7tfQ8Mk3LJURUU5S1Q0Q09MT09RVkFaVkFRMEhXTFJZQy4u"
        - text: "Call for Speakers"
          file: earthday2025_callforspeakers.qmd


format:
  html:
    theme: spacelab
    linkcolor: green
    linkhovercolor: purple
#      light: flatly
#      dark: darkly
    css: styles.css
#    fontsize: 1.1rem
    toc: true



